### ISSUE TITLE
JavaFX

### ISSUE THREAD

**Issue by Armiady** [RamAlapure/JavaFXSpringBootApp#1]
Sir! How to do CRUD in JavaFX?

**Comment by RamAlapure** [comment]
Have you tried this repository code running on your machine? because this repository has all the code that demonstrates the CRUD with the Sring Boot and JavaFX. Video link to this code demonstration on my youtube channel - https://youtu.be/NQQOPy-jmhA

If you are looking only specific for JavaFX you can go through my other repository [User-Details-Application-JavaFX-8-Tutorials](https://github.com/RamAlapure/User-Details-Application-JavaFX-8-Tutorials) which has more than CRUD.
